version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        image: nginx
        ports:
            - "8098:80"
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - fpm
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
             - postgresql_db

    postgresql_db:
        image: postgres:13.3
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root


